### ISSUE TITLE
[BUG] Plugin Completely Broken 

### ISSUE THREAD

**Issue by naveen-pcs** [solar2d/com.solar2d-plugin.amazon.iap.v3#2]
I've been trying to integrate the plugin and it keep failing immediately. Upon calling store.init(), I do receive store.isActive = true, but literally every single request made such as store.loadProducts() and store.purchase() always fails.

None of the API calls work at all without giving errors. The error logs are not useful since they provide no additional info. The same issues occur in both debug and live production builds. 

![IMG_2723](https://github.com/solar2d/com.solar2d-plugin.amazon.iap.v3/assets/4209764/86310c00-cec1-4f56-bc4b-01a066ae1efc)

It seems that nobody is having luck with this plugin, as evidenced by this thread from 2023: https://forums.solar2d.com/t/store-init-will-not-connect-to-amazon-app-tester/355331

**Comment by YvanDotet** [comment]
Hello did this issue will be fix pleased ? We can't sell in app purchase with this.

Thanks you.

**Comment by naveen-pcs** [comment]
I still haven't been able to get it working. Even using the old legacy plugin doesn't work for me (won't even respond to store.loadProducts). Let me know if you figure something out!

**Comment by YvanDotet** [comment]
Hello @naveen-pcs 
I have answered to you at solar2d-forum : https://forums.solar2d.com/t/amazon-iap-v3-broken/356349/13

Sincerely,
Yvan.

**Comment by scottrules44** [comment]
This should have been fixed btw sorry for late reply
